### ISSUE TITLE
Updating other firmware

### ISSUE THREAD

**Issue by scallas** [arduino-libraries/UnoWiFi-FirmwareUpdater-Plugin#4]
Is there anyway to update other firmware with the updater tool (ie not 0.03/0.02/0.01)
Cheers

**Comment by sergiotomasello** [comment]
nope @scallas 
you could try to manually use the included binary under the bin folder. It's a binary based on [esptool.py](https://github.com/espressif/esptool/releases/tag/v1.3)
regards
